# ?????? ?? ? ?? ??
spring.profiles.active=dev
server.address=0.0.0.0
spring.application.name=jigu_travel
server.port=${PORT:8080}
server.servlet.encoding.force-response=true

# H2 ?????? ??
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=1234
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Hibernate ??
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ?? ?? (SQL ?? ???)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT ??
jwt.secret=bXlTdXBlclNlY3JldEtleUZvckpXVUF1dGhlbnRpY2F0aW9uMTIzIQ==
jwt.access-expiration=360000
jwt.refresh-expiration=604800000

# ?? ?? ??
logging.level.root=INFO
logging.level.com.project_merge=DEBUG


#fast api host : ?? Url ??
ai-guide.api.host = http://localhost:8000

# multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.hibernate.orm.jdbc.bind=TRACE